# Generated by Django 4.1.1 on 2022-09-07 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('due_date', models.DateTimeField(null=True)),
                ('complete_date', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('CREATED', 'CREATED'), ('FINISHED', 'FINISHED')], max_length=45)),
            ],
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
